### ISSUE TITLE
Reads ping, hangs on speed test, Kodi 20 RC2

### ISSUE THREAD

**Issue by siliconhippy** [add-ons/script.speedtester#26]
Hi !

I used AE-PCx86-11.0.18 Kodi 20 beta ( from AlexElec.tv repo, a fork of CoreElec) and  the Speedtest addon worked fine.

However with the AE 11.0.19 version with Kodi 20 RC2, the addon shows ping but hangs at the speed test part. 
See Kodi error log pic attached.

![IMG_20230115_023632](https://user-images.githubusercontent.com/42253841/212531383-a32fb16e-6f8b-47f2-bce3-c0a22fd9b332.jpg)

**Comment by newf276** [comment]
Same issue on LibreELEC Nexus final, and Kodi final Nexus for both Android and OSX.  Ping only, but does not calculate speed .. No error log, as one is not produced.

**Comment by strolch89** [comment]
SOLVED!

Same issue. LibreELEC 20.1-Nexus on RPI4. Ping only but no speedtest.

```
2023-05-03 12:29:28.012 T:805      info <general>: Loading skin file: /storage/.kodi/addons/script.speedtester/resources/skins/Default/720p/script-speedtester_main.xml, load type: LOAD_ON_GUI_INIT
2023-05-03 12:29:33.365 T:1284    error <general>: Exception in thread 
2023-05-03 12:29:33.366 T:1284    error <general>: Thread-2 (consumer)
2023-05-03 12:29:33.366 T:1284    error <general>: :
                                                   
2023-05-03 12:29:33.366 T:1284    error <general>: 
2023-05-03 12:29:33.366 T:1284    error <general>: Traceback (most recent call last):
                                                   
2023-05-03 12:29:33.366 T:1284    error <general>: 
2023-05-03 12:29:33.366 T:1284    error <general>:   File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
                                                   
2023-05-03 12:29:33.367 T:1284    error <general>: 
2023-05-03 12:29:33.367 T:1284    error <general>:   File "/usr/lib/python3.11/threading.py", line 975, in run
                                                   
2023-05-03 12:29:33.374 T:1284    error <general>: 
2023-05-03 12:29:33.374 T:1284    error <general>:   File "/storage/.kodi/addons/script.speedtester/resources/lib/addon.py", line 738, in consumer
                                                   
2023-05-03 12:29:33.389 T:1284    error <general>: 
2023-05-03 12:29:33.389 T:1284    error <general>:     
2023-05-03 12:29:33.389 T:1284    error <general>: while thread.isAlive():
2023-05-03 12:29:33.389 T:1284    error <general>: 
                                                   
2023-05-03 12:29:33.389 T:1284    error <general>: 
2023-05-03 12:29:33.389 T:1284    error <general>:  
2023-05-03 12:29:33.389 T:1284     info <general>: Skipped 9 duplicate messages..
2023-05-03 12:29:33.389 T:1284    error <general>: ^
2023-05-03 12:29:33.390 T:1284     info <general>: Skipped 13 duplicate messages..
2023-05-03 12:29:33.390 T:1284    error <general>: 
                                                   
2023-05-03 12:29:33.390 T:1284    error <general>: 
2023-05-03 12:29:33.390 T:1284    error <general>: AttributeError
2023-05-03 12:29:33.390 T:1284    error <general>: : 
2023-05-03 12:29:33.390 T:1284    error <general>: 'FileGetter' object has no attribute 'isAlive'
2023-05-03 12:29:33.390 T:1284    error <general>: . Did you mean: '
2023-05-03 12:29:33.390 T:1284    error <general>: is_alive
2023-05-03 12:29:33.390 T:1284    error <general>: '?
2023-05-03 12:29:33.390 T:1284    error <general>: 
                                                   
2023-05-03 12:29:33.443 T:1279    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'Thread' object has no attribute 'isAlive'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.speedtester/resources/lib/addon.py", line 658, in onClick
                                                       self.speedtest(share=True, simple=True)
                                                     File "/storage/.kodi/addons/script.speedtester/resources/lib/addon.py", line 860, in speedtest
                                                       dlspeed = self.download_speed(urls, simple)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.speedtester/resources/lib/addon.py", line 752, in download_speed
                                                       while prod_thread.isAlive():
                                                             ^^^^^^^^^^^^^^^^^^^
                                                   AttributeError: 'Thread' object has no attribute 'isAlive'
                                                   -->End of Python script error report<-
```

To solve this, just as ajbathe in another thread recommends. I changed `isAlive()` into `is_alive()` in multiple lines in the script. Now it workes fine for me.
Thank you ajbathe.

**Comment by atrugiel69** [comment]
The above solition worked for me too. It should be merged.
