### ISSUE TITLE
addon not working with omega and nexus

### ISSUE THREAD

**Issue by shanestonk** [add-ons/script.speedtester#30]
The addon can be install with kodi repo and run but no speedtest work

**Comment by githans1** [comment]
Same for me. I do get a ping, but no download speed test is started

**Comment by klyco** [comment]
Same for me.
Log is:
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'tuple' object has no attribute 'read'
                                                   Traceback (most recent call last):
                                                     File "C:\Kodi\portable_data\addons\script.speedtester\resources\lib\addon.py", line 658, in onClick
                                                       self.speedtest(share=True, simple=True)
                                                     File "C:\Kodi\portable_data\addons\script.speedtester\resources\lib\addon.py", line 820, in speedtest
                                                       servers = closest_servers(config['client'])
                                                     File "C:\Kodi\portable_data\addons\script.speedtester\resources\lib\addon.py", line 237, in closest_servers
                                                       serversxml.append(handler.read(10240))
                                                   AttributeError: 'tuple' object has no attribute 'read'


Cheers,
Ken

**Comment by klyco** [comment]
Looks like either 1)  The URL being used is not returning any data OR 2) The data returned is not what the code is expecting.
Not sure if this is being maintained but hopefully it is a minor fix.
